import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navBar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100"]
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
     <body className="h-full w-full">
      <div className= "h-full w-full flex items-center">
        <NavBar/>
        <div className="h-[97%] w-[93%] flex bg-white drop-shadow -ml-4 mr-2 rounded-3xl ">{children}</div>
       </div>
     </body>
    </html>
  );
}
